FROM openjdk:21-jdk-slim

WORKDIR /app

COPY target/crud_cinema-0.0.1-SNAPSHOT.jar app.jar

ENV SPRING_APPLICATION_NAME=
ENV SPRING_DATASOURCE_URL=
ENV SPRING_DATASOURCE_USERNAME=
ENV SPRING_DATASOURCE_PASSWORD=
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=
ENV SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=

ENTRYPOINT ["java", "-jar", "app.jar"]
